### ISSUE TITLE
reset dialog styles

### ISSUE THREAD

**Issue by mayank99** [mayank99/reset.css#11]
every time i work with `<dialog>`, i have to blow away all of its useless default styles, so it would be nice if the reset took care of it.

the only part i'm unsure about is what to do with the `[open]` attribute. `display: none !important;` makes sense on it, but the `!important` being in a reset could be problematic in case the dialog needs to be animated (e.g. using `visibility: hidden`). although, `display: none` will soon be animateable, and `@starting-style` could be helpful too?

TBD

**Comment by mayank99** [comment]
chrome 117 ships on september 12 https://developer.chrome.com/blog/entry-exit-animations/

**Comment by brookback** [comment]
Maybe this is a new issue, but:

## `* { margin: 0 }` is problematic for dialogs: resets center positioning

The `<dialog>` element has built-in margin from the user agent, which makes it centered in the viewport. The `margin: 0` set on `*` in this package undoes that styling.

### Repro

```html
<!doctype html>
<html>
    <head>
        <style>
            @import "https://unpkg.com/@acab/reset.css@0.8.0/index.css";
        </style>
    </head>
    <body>
        <dialog id="modal">
            <p>Hi there</p>
        </dialog>

        <button id="show" onclick="window.modal.showModal()">Show modal</button>
    </body>
</html>
```

### Actual

<img width="908" alt="image" src="https://github.com/mayank99/reset.css/assets/30257156/f9ba8467-7a24-450b-ac27-1a8bf1f22da1">

### Expected

<img width="908" alt="image" src="https://github.com/mayank99/reset.css/assets/30257156/dffe1c0b-707a-4b81-9b30-7b3720f58746">

***

A workaround is either:

```css
dialog {
  margin: auto;
}
```
or selectively apply `margin: 0` to common elements.

Here's what I'm currently going with:

```css
:where(html, body, blockquote, dl, dd, h1, h2, h3, h4, h5, h6, hr, figure, p, pre, ol, ul, fieldset) {
  margin: 0;
}

:where(html, body, ol, ul, fieldset) {
  padding: 0;
}
```
