### ISSUE TITLE
Duplicated `resize` property of `textarea`

### ISSUE THREAD

**Issue by baseballyama** [mayank99/reset.css#4]
I'm not familiar with CSS, but below code duplicating is correct?

I think it should be like this?

```css
 :where(textarea) { 
 	resize: vertical;
 } 
```

https://github.com/mayank99/reset.css/blob/fd9668d7340478e97896a63291b6ffb064edd776/package/index.css#L43-L46
